// Copyright 2026 Orkia
// SPDX-License-Identifier: Elastic-2.0
//
// This file is part of the public Orkia shell. Licensed under the
// Elastic License 2.0 — see the top-level LICENSE file for
// the Elastic License 2.0 terms.

//! Install a scripted TUI agent into the sandbox.
//!
//! Writes `<sandbox>/.orkia/agents/<name>/agent.toml` pointing the
//! `[runtime] command` at the compiled `orkia-fake-agent` binary, plus
//! a `script.yaml` next to it that the agent reads on startup.
//!
//! The agent.toml schema we emit is the minimum surface the orkia
//! agent-loader requires (`[agent].name`, `[runtime].command`,
//! `[runtime].args`, `[hooks].provider`). Optional sections are
//! omitted so the harness keeps working when the surrounding schema
//! evolves under your hands.

use std::path::PathBuf;

use crate::sandbox::OrkiaSandbox;
use crate::script::AgentScript;

pub struct ScriptedAgent {
    pub name: String,
    pub dir: PathBuf,
    pub script_path: PathBuf,
}

impl ScriptedAgent {
    /// Start a new builder for `name`.
    pub fn builder(name: impl Into<String>) -> ScriptedAgentBuilder {
        ScriptedAgentBuilder {
            name: name.into(),
            script: AgentScript::default(),
            hooks_provider: Some("claude".into()),
            extra_args: Vec::new(),
        }
    }
}

pub struct ScriptedAgentBuilder {
    name: String,
    script: AgentScript,
    hooks_provider: Option<String>,
    extra_args: Vec<String>,
}

impl ScriptedAgentBuilder {
    /// Replace the script wholesale.
    pub fn script(mut self, s: AgentScript) -> Self {
        self.script = s;
        self
    }

    /// Set the `[hooks].provider` value (claude, codex, gemini, none).
    /// Defaults to "claude". Pass `None` for no provider.
    pub fn hooks_provider(mut self, p: Option<&str>) -> Self {
        self.hooks_provider = p.map(str::to_string);
        self
    }

    /// Additional CLI args appended after `--script <path>` when the
    /// agent is spawned. Useful to opt-in to fake-agent debug logging.
    pub fn extra_args(mut self, args: impl IntoIterator<Item = impl Into<String>>) -> Self {
        self.extra_args = args.into_iter().map(Into::into).collect();
        self
    }

    /// Materialise the agent inside the sandbox. `fake_agent_bin` must
    /// be an absolute path to the compiled `orkia-fake-agent`.
    pub fn install(
        self,
        sandbox: &OrkiaSandbox,
        fake_agent_bin: &std::path::Path,
    ) -> anyhow::Result<ScriptedAgent> {
        let dir = sandbox.agent_dir(&self.name);
        std::fs::create_dir_all(&dir)?;

        let script_path = dir.join("script.yaml");
        std::fs::write(&script_path, self.script.to_yaml()?)?;

        let mut args = vec!["--script".to_string(), script_path.display().to_string()];
        args.extend(self.extra_args);

        let toml = render_agent_toml(
            &self.name,
            fake_agent_bin,
            &args,
            self.hooks_provider.as_deref(),
        );
        std::fs::write(dir.join("agent.toml"), toml)?;

        Ok(ScriptedAgent {
            name: self.name,
            dir,
            script_path,
        })
    }
}

fn render_agent_toml(
    name: &str,
    command: &std::path::Path,
    args: &[String],
    hooks_provider: Option<&str>,
) -> String {
    let mut s = String::new();
    s.push_str("# Generated by orkia-test-harness — do not edit.\n");
    s.push_str("[agent]\n");
    s.push_str(&format!("name = \"{name}\"\n"));
    s.push_str("archetype = \"general\"\n");
    s.push_str("description = \"orkia-test-harness scripted agent\"\n\n");

    s.push_str("[runtime]\n");
    s.push_str(&format!("command = \"{}\"\n", command.display()));
    s.push_str("args = [");
    for (i, a) in args.iter().enumerate() {
        if i > 0 {
            s.push_str(", ");
        }
        // basic TOML string escaping for the limited chars we emit
        let escaped = a.replace('\\', "\\\\").replace('"', "\\\"");
        s.push_str(&format!("\"{escaped}\""));
    }
    s.push_str("]\n\n");

    if let Some(p) = hooks_provider {
        s.push_str("[hooks]\n");
        s.push_str(&format!("provider = \"{p}\"\n\n"));
    }

    s.push_str("[trust]\n");
    s.push_str("score = 1.0\n");

    s
}
