// Copyright 2026 Orkia
// SPDX-License-Identifier: Elastic-2.0
//
// This file is part of the public Orkia shell. Licensed under the
// Elastic License 2.0; see the top-level LICENSE file
// for terms.

//! Filesystem bootstrap for `~/.orkia/` and agent directories.
//!
//! `create_base_dirs` is idempotent so re-running `orkia setup` (or the
//! first-launch auto-prompt after a decline) never wipes anything.
//! `scaffold_agent` is the setup-side equivalent of
//! `crates/orkia-shell/src/repl.rs::handle_agent_create` and produces
//! the same 4-file layout the loader expects.

use std::io;
use std::path::{Path, PathBuf};

use orkia_builtin::agent_templates;

use super::registry::{ArchetypeMeta, ArchetypeSource};

const DEFAULT_CONFIG: &str = "# Orkia Shell Configuration
# Generated by `orkia setup`. Safe to edit by hand.

# Source ~/.bashrc on startup (non-login shells).
load_bashrc = true
# Source the .profile chain for login shells.
load_profile = true

# default_mode = \"shell\"     # \"shell\" or \"tui\"
# default_project = \"\"
";

/// Ensure `<orkia_dir>` and its subdirectories exist. Creates the empty
/// log files and a default `config.toml` only when they're absent so
/// repeat calls are safe.
pub fn create_base_dirs(orkia_dir: &Path) -> io::Result<()> {
    for sub in ["", "agents", "projects", "run", "registry"] {
        std::fs::create_dir_all(orkia_dir.join(sub))?;
    }
    for (name, body) in [("seal.jsonl", ""), ("journal.jsonl", ""), ("history", "")] {
        let path = orkia_dir.join(name);
        if !path.exists() {
            std::fs::write(&path, body)?;
        }
    }
    let config_path = orkia_dir.join("config.toml");
    if !config_path.exists() {
        std::fs::write(&config_path, DEFAULT_CONFIG)?;
    }
    Ok(())
}

/// Materialize an agent under `<orkia_dir>/agents/<name>/`. Returns the
/// path on success; errors are propagated so the wizard can show them.
///
/// loader in `crates/orkia-shell/src/agent_dir.rs`:
/// - `agent.toml`        — runtime + trust + context config
/// - `system-prompt.md`  — archetype prompt with `{name}` substituted
/// - `memory.md`         — empty stub with today's date
/// - `tools.toml`        — empty MCP/tools placeholder
pub fn scaffold_agent(
    agents_dir: &Path,
    archetype: &ArchetypeMeta,
    agent_name: &str,
    cli_tool: &str,
) -> io::Result<PathBuf> {
    let dir = agents_dir.join(agent_name);
    if dir.exists() {
        return Err(io::Error::new(
            io::ErrorKind::AlreadyExists,
            format!("agent '{agent_name}' already exists"),
        ));
    }
    std::fs::create_dir_all(&dir)?;
    std::fs::write(
        dir.join("agent.toml"),
        render_agent_toml(
            agent_name,
            &archetype.name,
            &archetype.description,
            cli_tool,
        ),
    )?;
    std::fs::write(
        dir.join("system-prompt.md"),
        render_system_prompt(archetype, agent_name),
    )?;
    std::fs::write(
        dir.join("memory.md"),
        render_empty_memory(&chrono::Utc::now().format("%Y-%m-%d").to_string()),
    )?;
    std::fs::write(dir.join("tools.toml"), EMPTY_TOOLS)?;
    Ok(dir)
}

fn render_agent_toml(name: &str, archetype: &str, description: &str, cli_tool: &str) -> String {
    format!(
        "[agent]\nname = \"{name}\"\ndescription = \"{desc}\"\narchetype = \"{archetype}\"\n\n\
         [runtime]\ncommand = \"{cli_tool}\"\nargs = []\n\n\
         [trust]\nscore = 0.70\n\n\
         [projects]\nassigned = []\n\n\
         [context]\nmax_context_tokens = 4000\ninclude_rfcs = true\ninclude_issues = true\n",
        desc = escape_toml(description),
    )
}

fn render_system_prompt(archetype: &ArchetypeMeta, agent_name: &str) -> String {
    match &archetype.source {
        ArchetypeSource::Registry(dir) => {
            let path = dir.join("system-prompt.md");
            match std::fs::read_to_string(&path) {
                Ok(template) => substitute_name(&template, agent_name),
                Err(_) => agent_templates::generate_prompt_template(agent_name, &archetype.name),
            }
        }
        ArchetypeSource::Builtin => {
            agent_templates::generate_prompt_template(agent_name, &archetype.name)
        }
    }
}

fn substitute_name(template: &str, agent_name: &str) -> String {
    let cap = capitalize(agent_name);
    template
        .replace("{name}", &cap)
        .replace("{Name}", &cap)
        .replace("{NAME}", &agent_name.to_uppercase())
}

fn capitalize(s: &str) -> String {
    let mut chars = s.chars();
    match chars.next() {
        Some(c) => c.to_uppercase().collect::<String>() + chars.as_str(),
        None => String::new(),
    }
}

fn render_empty_memory(date: &str) -> String {
    format!("# Memory\n\n## {date}\n- Agent created via orkia setup\n")
}

const EMPTY_TOOLS: &str = "# MCP servers and tools for this agent\n# [[mcp]]\n# name = \"github\"\n# url = \"https://mcp.github.com/sse\"\n";

fn escape_toml(s: &str) -> String {
    s.replace('\\', "\\\\").replace('"', "\\\"")
}

#[cfg(test)]
mod tests {
    use super::*;
    use tempfile::TempDir;

    fn builtin(name: &str) -> ArchetypeMeta {
        ArchetypeMeta {
            name: name.into(),
            description: "test desc".into(),
            suggested_names: vec!["faye".into()],
            preferred_cli: vec!["claude".into()],
            is_community: false,
            source: ArchetypeSource::Builtin,
        }
    }

    #[test]
    fn base_dirs_are_idempotent() {
        let tmp = TempDir::new().unwrap();
        let root = tmp.path().join(".orkia");
        create_base_dirs(&root).unwrap();
        std::fs::write(root.join("config.toml"), "user_edited = true").unwrap();
        std::fs::write(root.join("history"), "cmd one\n").unwrap();
        create_base_dirs(&root).unwrap();
        assert_eq!(
            std::fs::read_to_string(root.join("config.toml")).unwrap(),
            "user_edited = true"
        );
        assert_eq!(
            std::fs::read_to_string(root.join("history")).unwrap(),
            "cmd one\n"
        );
        for sub in ["agents", "projects", "run", "registry"] {
            assert!(root.join(sub).is_dir(), "missing {sub}");
        }
    }

    #[test]
    fn default_config_parses_as_shell_config() {
        let tmp = TempDir::new().unwrap();
        let root = tmp.path().join(".orkia");
        create_base_dirs(&root).unwrap();
        let body = std::fs::read_to_string(root.join("config.toml")).unwrap();
        let parsed: toml::Value = toml::from_str(&body).expect("default config must parse");
        assert_eq!(
            parsed.get("load_bashrc").and_then(|v| v.as_bool()),
            Some(true)
        );
    }

    #[test]
    fn scaffold_writes_all_four_files() {
        let tmp = TempDir::new().unwrap();
        let agents = tmp.path().join("agents");
        std::fs::create_dir_all(&agents).unwrap();
        let dir = scaffold_agent(&agents, &builtin("software-eng"), "faye", "claude").unwrap();
        for f in ["agent.toml", "system-prompt.md", "memory.md", "tools.toml"] {
            assert!(dir.join(f).is_file(), "missing {f}");
        }
        let prompt = std::fs::read_to_string(dir.join("system-prompt.md")).unwrap();
        assert!(prompt.contains("Faye"));
        assert!(!prompt.contains("{name}"));
        let toml_body = std::fs::read_to_string(dir.join("agent.toml")).unwrap();
        assert!(toml_body.contains("command = \"claude\""));
        assert!(toml_body.contains("archetype = \"software-eng\""));
    }

    #[test]
    fn scaffold_rejects_existing_dir() {
        let tmp = TempDir::new().unwrap();
        let agents = tmp.path().join("agents");
        std::fs::create_dir_all(agents.join("faye")).unwrap();
        let err = scaffold_agent(&agents, &builtin("devops"), "faye", "claude").unwrap_err();
        assert_eq!(err.kind(), io::ErrorKind::AlreadyExists);
    }

    #[test]
    fn registry_prompt_template_substitutes_name() {
        let tmp = TempDir::new().unwrap();
        let arch_dir = tmp.path().join("rust-specialist");
        std::fs::create_dir_all(&arch_dir).unwrap();
        std::fs::write(
            arch_dir.join("system-prompt.md"),
            "# {name} — Rust Specialist\n\nYou are {name}.\n",
        )
        .unwrap();
        let meta = ArchetypeMeta {
            name: "rust-specialist".into(),
            description: "Rust expert".into(),
            suggested_names: vec![],
            preferred_cli: vec!["claude".into()],
            is_community: true,
            source: ArchetypeSource::Registry(arch_dir),
        };
        let agents = tmp.path().join("agents");
        std::fs::create_dir_all(&agents).unwrap();
        let dir = scaffold_agent(&agents, &meta, "ferris", "claude").unwrap();
        let prompt = std::fs::read_to_string(dir.join("system-prompt.md")).unwrap();
        assert_eq!(prompt, "# Ferris — Rust Specialist\n\nYou are Ferris.\n");
    }
}
